apiVersion: v1
kind: Service
metadata:
  name: mysql-group-replication
  namespace: dba
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-group-replication
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: StatefulSet
metadata:
  name: mysql-group-replication
  namespace: dba
spec:
  selector:
    matchLabels:
      app: mysql-group-replication
  serviceName: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql-group-replication
    spec:
      initContainers:
      containers:
      - image: registry.dev.hbec.com/dba/mysql-group-replication:0.1
        name: mysql-group-replication
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-group-replication
              key: rootpassword
        - name: BACKUP_DOWNLOAD_FULL_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-group-replication
              key: BACKUP_DOWNLOAD_FULL_URL
        - name: BACKUP_DOWNLOAD_INC_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-group-replication
              key: BACKUP_DOWNLOAD_INC_URL
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-group-replication
  namespace: dba
type: Opaque
data:
  rootpassword: MTIzMTIz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-group-replication
  namespace: dba
data:
  BACKUP_DOWNLOAD_FULL_URL: http://rdsbak-hangzhou-finance.oss-cn-hzfinance.aliyuncs.com/custins7481335/hins5079413_data_20180818093300.tar.gz?OSSAccessKeyId=LTAITfQ7krsrEwRn&Expires=1534902156&Signature=LbTMFe5QIBk6cYyoRrTjbhhCc4U%3D
  BACKUP_DOWNLOAD_INC_URL: